# This is a basic workflow that is manually triggered

name: [codecov] Run coverage

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches:
    - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Run vitest coverage
      run: npx vitest run --coverage
